name = "mobile-iran"
main = "worker.js"
compatibility_date = "2026-10-03"

[[d1_databases]]
binding = "DB"
database_name = "mobile_iran_db"
database_id = "d56093cc-7343-4bac-8941-a8ba24321841"
