name = "mobile-iran"
main = "worker.js"
compatibility_date = "2026-10-03"

[[d1_databases]]
binding = "DB"
database_name = "mobile_iran_db"
database_id = "36c55b3b-bc58-4d03-8771-2358d6d5ae8b"
